In [2]:
from __future__ import print_function
import torch

In [3]:
# creating an empty 5 X 3 matrix
x = torch.empty(5, 3)
print(x)

tensor([[ 0.0000,  0.0000,  0.0000],
        [ 0.0000, -0.0000,  0.0000],
        [-0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000]])


In [4]:
# creating a random 5 X 3 matrix
x = torch.rand(5, 3)
print(x)

tensor([[0.9171, 0.3424, 0.1389],
        [0.6721, 0.8262, 0.0884],
        [0.0947, 0.6251, 0.1219],
        [0.2241, 0.5122, 0.1306],
        [0.1771, 0.3373, 0.1374]])


In [5]:
# empty matrix with long data type
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [6]:
# Constructing a tensor directly from data
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [7]:
# 5x3 matrix of ones 
# new_* method takes in the sizes
x = x.new_ones(5, 3, dtype=torch.double) 
print(x)

# override dtype 
# result has the same size
x = torch.randn_like(x, dtype=torch.float)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-0.6702,  1.6997, -1.4885],
        [ 0.3649,  0.5308,  1.1411],
        [ 0.6107, -0.4745,  0.7560],
        [ 1.3330, -1.1635,  0.8356],
        [ 1.5522,  0.3016,  1.0037]])


In [8]:
# get its size
print(x.size())

torch.Size([5, 3])


In [9]:
# Addition operation on two matrices
y = torch.rand(5, 3)
print(x + y)

tensor([[-0.1906,  2.6105, -1.0479],
        [ 0.7986,  1.3752,  1.2205],
        [ 1.3470, -0.0378,  1.6217],
        [ 1.8192, -0.6733,  1.7558],
        [ 2.1217,  0.5626,  1.4321]])


In [10]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[-0.1906,  2.6105, -1.0479],
        [ 0.7986,  1.3752,  1.2205],
        [ 1.3470, -0.0378,  1.6217],
        [ 1.8192, -0.6733,  1.7558],
        [ 2.1217,  0.5626,  1.4321]])


In [11]:
print(x[:, 1])

tensor([ 1.6997,  0.5308, -0.4745, -1.1635,  0.3016])


In [12]:
print(x)

tensor([[-0.6702,  1.6997, -1.4885],
        [ 0.3649,  0.5308,  1.1411],
        [ 0.6107, -0.4745,  0.7560],
        [ 1.3330, -1.1635,  0.8356],
        [ 1.5522,  0.3016,  1.0037]])


In [13]:
print(x[:, 0])

tensor([-0.6702,  0.3649,  0.6107,  1.3330,  1.5522])


In [14]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from the other dimention
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [15]:
print(x)
print(y)
print(z)


tensor([[-1.8191, -0.9226,  0.5218, -0.0650],
        [-1.9105,  0.9595, -1.3590,  1.4311],
        [ 1.7616,  0.2838,  0.6048,  1.9329],
        [-0.1266,  0.6070, -0.0919,  0.5382]])
tensor([-1.8191, -0.9226,  0.5218, -0.0650, -1.9105,  0.9595, -1.3590,  1.4311,
         1.7616,  0.2838,  0.6048,  1.9329, -0.1266,  0.6070, -0.0919,  0.5382])
tensor([[-1.8191, -0.9226,  0.5218, -0.0650, -1.9105,  0.9595, -1.3590,  1.4311],
        [ 1.7616,  0.2838,  0.6048,  1.9329, -0.1266,  0.6070, -0.0919,  0.5382]])


In [17]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([-0.2962])
-0.2961638271808624
